### ISSUE TITLE
use bookdown rmarkdown rather than just rmarkdown 

### ISSUE THREAD

**Issue by bnicenboim** [eddelbuettel/binb#30]
Hi!
I'm right now creating my slides with 
```
output: 
  bookdown::beamer_presentation2:
    keep_tex: yes
    theme: metropolis
    latex_engine: xelatex
    slide_level: 2
    incremental: no
    includes: 
      in_header: top-matter.tex
classoption: aspectratio=169
fontsize: 12pt
```
 in my YAML, it would be nice to automatize this, but I  binb doesn't use bookdown, right? 
There are many advantages in the bookdown flavor of rmarkdown including  numbering and cross-referencing figures/tables/sections/equations

I'm also including some hacks in the tex files that  could be included in binb, see https://bookdown.org/yihui/rmarkdown-cookbook/multi-column.html

What do you think? Should I do pull request with all these changes?
